plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
# remote_theme: "mmistakes/minimal-mistakes@4.21.0"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

title: Projects and Research
name: "Emil VATAI"
bio: "Emil's bio"
description: Mostly CS and Math

titles_from_headings:
  enabled: false

# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       author_profile: true

# author:
#   avatar   : "/assets/images/bio-photo.jpg"
#   bio      : "My awesome biography constrained to a sentence or two goes here."
#   location : "Tokyo, Japan"
#   links:
#     - label: "Made Mistakes"
#       icon: "fas fa-fw fa-link"
#       url: "https://mademistakes.com"
