title: Projects and Research
description: Mostly CS and Math

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
# remote_theme: "mmistakes/minimal-mistakes@4.21.0"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      
author:
  name     : "Emil VATAI"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Tokyo, Japan"
